### ISSUE TITLE
Non-GPT version allows some misidentified actors to still be included in the image prompt. 

### ISSUE THREAD

**Issue by GotAudio** [GotAudio/AudioBookSlides#2]
Add a new filter to prune potential characters from \<bookname\>_ts_p_characters.srt that were not included in \<bookname\>_ts_p_actors.txt either due to "depth" setting or user deletion. Also ensure user age and gender settings take precedence over defaults.  (Because unknown gender defaults to {creature} which takes priority in default_config.yaml, and characters with the lowest occurrence count are prioritized in \<bookname\>_ts_p.srt.) This causes place names (like "Ravenclaw") to be interpreted as a 24yo female or creature, instead of a house in Hogwarts.  **A workaround is to change config actor_priority: to "actress, actor, female, creature"**  That should at least prevent this issue from overriding configured actors.  Verify this behavior does not occur in GPT version too.

**Comment by NIKHTU01** [comment]
can i please have this link of colab notebook?

**Comment by GotAudio** [comment]
I already replied to your first request.  Stable Diffusion does not run in colab.  Google does not allow it.
